version: "3"

services:
  app:
    container_name: toughts-app
    build: .
    command: yarn dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    expose:
      - "3000"

  mysql:
    container_name: toughts-mysql
    image: mysql:8.0.30
    security_opt:
      - seccomp:unconfined
    volumes:
      - "./.data/db:/var/lib/mysql"
    # command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toughts
      MYSQL_DATABASE: toughts
      TZ: America/Sao_Paulo
    expose:
      - "3306"
      
volumes:
  mysql:
    driver: local